version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/v2"
      - "/cmd"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
    groups:
      shared-dependencies:
        group-by: "dependency-name"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
