on: [ push, pull_request ]
name: Go Fuzz

jobs:
  v1:
    strategy:
      fail-fast: true
      matrix:
        target: [ "CarReader" ]
    runs-on: ubuntu-latest
    name: Fuzz V1 ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Go information
        run: |
          go version
          go env
      - name: Run Fuzzing for 1m
        run: go test -v -fuzz=Fuzz${{ matrix.target }} -fuzztime=1m .
  v2:
    strategy:
      fail-fast: true
      matrix:
        target: [ "BlockReader", "Reader", "Index", "Inspect" ]
    runs-on: ubuntu-latest
    name: Fuzz V2 ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Go information
        run: |
          go version
          go env
      - name: Run Fuzzing for 1m
        run: |
          cd v2
          go test -v -fuzz=Fuzz${{ matrix.target }} -fuzztime=1m .
